### ISSUE TITLE
coupling dplyr's progress bar with shiny progress bar

### ISSUE THREAD

**Issue by mlist** [hadley/dplyr#1005]
It would be really nice if the progress bar could be hooked up with the shiny progress bar, e.g. dplyr should accept an update function. This would enable developers to give their users a much more detailed feedback in shiny apps when using dplyr.

**Comment by hadley** [comment]
I agree, but it's unlikely to happen in the near future :/

**Comment by johnbwilliams** [comment]
Any updates on capability to implement a progress bar in a shiny renderXXX functions implemented with dplyr pipelines?

**Comment by sebpardo** [comment]
I would love to see this implemented, although I acknowledge it would be a fair amount of work for a small feature.

I wonder what it would conceptually look like for dplyr functions to permit this. Perhaps another way would be enabling dplyr functions to explicitly return the progress counter instead of just printing it?
