### ISSUE TITLE
bind_rows(): accept lists?

### ISSUE THREAD

**Issue by jennybc** [hadley/dplyr#1104]
[This tweet](https://twitter.com/hadleywickham/status/591620579465293824) reminded me of this wish.

Sometimes I am disappointed that `bind_rows()` insists that its input already be data.frames. In that sense, it's not a drop-in replacement for `data.table::rbindlist()`. Any chance `bind_rows()` might accept a list of lists?

```
> my_list <- list(list(x = 1, y = 'a'), list(x = 2, y = 'b'))
> data.table::rbindlist(my_list) %>% str
Classes ‘data.table’ and 'data.frame':	2 obs. of  2 variables:
 $ x: num  1 2
 $ y: chr  "a" "b"
 - attr(*, ".internal.selfref")=<externalptr> 

> dplyr::bind_rows(my_list)
Error: object at index 1 not a data.frame
```

**Comment by romainfrancois** [comment]
I can probably relax that a bit. starting from here: 

```
List rbind_all( StrictListOf<DataFrame, NULL_or_Is<DataFrame> > dots ){
    return rbind__impl(dots) ;
}
```

Maybe instead of a `StrictListOf<DataFrame, NULL_or_Is<DataFrame> >` I could use something like a `StrictListOf<Bindable>` where Bindable is allowed to be `NULL`, a `data.frame`  or a list with some constraints, e.g. that all the components have equal lengths or something.

**Comment by hadley** [comment]
I think it would be reasonable to accept:

* NULL (ignore)
* data frame (as currently)
* a named list where each element is the same length

Maybe call it dataframeable or something like that? dataframeish?  

(If we accept lists and null here, we should consider doing it for other verbs too, although maybe it's not so important because `bind_rows()` is usually done once early in the data import process)

**Comment by lionel-** [comment]
But then how is `bind_rows()` going to be able to make the difference between a list to be taken as a data frame and a list of data frames, in case this list happens to be named? Wouldn't the data frames be taken as components of a list-column inside one dataframeable list, instead of a list of data frames to bind together?

Also linked to #992 if it gets merged.

**Comment by Mullefa** [comment]
+1 for accepting `NULL`'s. 

As an example, it would be convenient if both these cases returned the `iris` data set (similar functionality to `rbind()` in this respect):

```R
bind_rows(iris, NULL)
bind_rows(list(iris, NULL))
```

**Comment by jennybc** [comment]
Related wish for the new and improved `bind_rows()`: an ID variable. If you are row binding a list of data.frames or conformable lists, there's a high chance you want the names from the original list to come in as a variable in the result. This is one of the very best things about, e.g., `plyr::ldply()`, which I still resort to often in `dplyr`-ish projects.

**Comment by lionel-** [comment]
I wrote a PR for this, #825, which will need to be adapted to what I did in #992 (if it is still relevant).
