### ISSUE TITLE
monetdb: mutate() fails to generate correct window expression

### ISSUE THREAD

**Issue by ajdamico** [hadley/dplyr#1165]
# start in an empty directory somewhere
	# setwd( "C:/My Directory/MonetDB" )

	# # # # # # # # # START OF SETUP - no editing required

	library(dplyr)
	library(MonetDB.R)

	batfile <-
		monetdb.server.setup(
			database.directory = paste0( getwd() , "/MonetDB" ) ,
			monetdb.program.path = 
				ifelse( 
					.Platform$OS.type == "windows" , 
					"C:/Program Files/MonetDB/MonetDB5" , 
					"" 
				) ,
			dbname = "test" ,
			dbport = 50000
		)

	pid <- monetdb.server.start( batfile )

	my_db <- src_monetdb( dbname = "test" , port = 50000 , wait = TRUE )
	db <- dbConnect( MonetDB.R() , "monetdb://localhost:50000/test" )
	dbWriteTable( db , 'mtcars' , mtcars )

	my_tbl <- tbl( my_db , 'mtcars' )

	# # # # # # # # # END OF SETUP

	# this works fine
	my_tbl %>% 
		group_by( cyl , gear ) %>% 
		summarise( n = n() )

	# this works fin
	my_tbl %>% 
		group_by( cyl , gear ) %>% 
		summarise( n = n() )

		
	# this discussion has a few examples that i think *should* work
	# https://stackoverflow.com/questions/25881391/dplyr-counts-percentages-of-factor-grouped-by-school-not-getting-grouped

	# now the following two blocks break, both with this error

	# Error in .local(conn, statement, ...) : 
	  # Unable to execute statement 'SELECT "cyl", "gear", "n", (100.0 * "n") / SUM("n") AS "pct"
	# FROM (SELECT "cyl", "gear", COUNT(*) AS...'.
	# Server says '!cannot use non GROUP BY column 'cyl' in query results without an aggregate function'.

	my_tbl %>%
		group_by( cyl , gear ) %>%
		tally %>%
		group_by( cyl ) %>%
		mutate( pct = ( 100 * n ) / sum( n ) )
		

	my_tbl %>% 
		group_by( cyl , gear ) %>% 
		summarise( n = n() ) %>% 
		mutate( pct = 100 * n / sum( n ) )

**Comment by hadley** [comment]
@hannesmuehleisen any thoughts?

**Comment by hannesmuehleisen** [comment]
Will investigate....

**Comment by hannesmuehleisen** [comment]
The query that is being generated here is something along the following lines:

````
WITH "_W3" AS (SELECT "cyl", "gear", COUNT(*) AS "n" FROM "mtcars" GROUP BY "cyl", "gear") 
SELECT "cyl", "gear", "n", 100.0 * "n" / "sumn" AS "pct" FROM  "_W3", 
(SELECT SUM("n") as "sumn" FROM "_W3") AS "_W4";
````

The problem is that `SUM` is an aggregation function, which leads to an implicit aggregation with a single group (Nothing to to with MonetDB, SQL semantics). However, if an aggregation is present, all columns that are not grouping variables need to be aggregated (otherwise, no way to change row cardinality). As you can see, `cyl`, `gear` and `n` have no aggregation on them, hence the DB complains. There is unfortunately no real nice solution to this. The nicest I can come up with is

So a solution to this would be to outsource aggregations to a different subselect, join and then project.

**Comment by hadley** [comment]
I think this is the same problem as #1413. A minimal reprex would be appreciated.
