### ISSUE TITLE
Right way to support a case-phobic backend

### ISSUE THREAD

**Issue by piccolbo** [hadley/dplyr#1198]
I was wondering if I could get some suggestions about methods that need to be overridden to support a backend (sparkSQL) that has an interesting behavior wrt upper/lower case, which is not sensitivity or insensitivity, but drive-programmer-crazy-ivity:

```
> copy_to(my_db, mtcars, "MTCARS")
Error: Table MTCARS not found in database 
> my_db
src:  localhost:10000
tbls: mtcars
```

Another implicit conversion happens for field names

```
 copy_to(my_db, data.frame(A = 1, a = 2), "fieldtest")
Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  : 
  Unable to retrieve JDBC result set for CREATE TABLE  fieldtest  ( A  DOUBLE,  a  DOUBLE) (org.apache.spark.sql.execution.QueryExecutionException: FAILED: SemanticException [Error 10036]: Duplicate column name: a)
> copy_to(my_db, data.frame(A = 1, B = 2), "fieldtest")
Source: localhost:10000
From: fieldtest [1 x 2]

  a b
1 1 2
> fieldtest = tbl(my_db, "fieldtest")
> fieldtest
Source: localhost:10000
From: fieldtest [1 x 2]

  a b
1 1 2
> select(fieldtest, A)
Error in eval(expr, envir, enclos) : object 'A' not found
> select(fieldtest, a)
Source: localhost:10000
From: fieldtest [1 x 1]

  a
1 1

```

So field name  gets lowercased on creation, like table names, but in other contexts case matters. I tried to conver to lower with warning in db_create_table and db_save_query and in the src-specific tbl method, but it seems overkill and to be lowercasing entire sql statements, which doesn't hurt but shows I did not find the correct entry points, and doesn't do anything fro field names. Thanks

**Comment by hadley** [comment]
I don't have any great ideas unfortunately. I think ideally this would be taken care of at the DBI level - maybe the DBItest package by @krlmlr would be helpful at making sure the low level semantics are correct?

In the long term, a lot of the S3 generics will disappear from dplyr, shifting as much of the work as possible to the database backend and the DBI generics. I made the dplyr generics because there was so much variation across database interfaces, but it's definitely better to fix upstream so that everyone benefits from the consistency.
