### ISSUE TITLE
mutate_ with a single row data table and a list column fails

### ISSUE THREAD

**Issue by richierocks** [hadley/dplyr#1255]
This is OK:

```{r}
DT <- data.table(x = c("1;2", "3;4;5"))
DT %>% mutate_(y = ~ strsplit(x, ";"))
##        x     y
## 1:   1;2   1,2
## 2: 3;4;5 3,4,5
```

If there is only one row, I get an incorrect result, with a warning:

```{r}
DT[1,] %>% mutate_(y = ~ strsplit(x, ";"))
##      x y
## 1: 1;2 1
## Warning message:
## In `[.data.table`(`_dt`, , `:=`(y, strsplit(x, ";")), by = `_vars`) :
##   Supplied 2 items to be assigned to 1 items of column 'y' (1 unused)
```

The problem doesn't occur with data frames.

**Comment by romainfrancois** [comment]
It seems like a problem in `data.table` or a design decision, idk : 

```
> DT <- data.table(x = c("1;2", "3;4;5"))
> d <- DT[1,]
> ( d[ , y := strsplit(x, ";") ] )
     x y
1: 1;2 1
Warning message:
In `[.data.table`(d, , `:=`(y, strsplit(x, ";"))) :
  Supplied 2 items to be assigned to 1 items of column 'y' (1 unused)
```

ping @arunsrinivasan @mattdowle

**Comment by arunsrinivasan** [comment]
@romainfrancois thanks for the ping. Filed #1262.

**Comment by arunsrinivasan** [comment]
data.table also allows assignments of the form `DT[, (cols) := list(vals)]` which `mutate` doesn't/can't AFAICT. 

For `mutate` to work properly with data.tables, seems like you should construct `\`:=\`(lhs = rhs)` In `mutate_.data.table`, instead of `\`:=\`(lhs, rhs)` (current). Closing https://github.com/Rdatatable/data.table/issues/1262
