### ISSUE TITLE
db_insert_into for remote mysql

### ISSUE THREAD

**Issue by piccolbo** [hadley/dplyr#1383]
Hi,
I noticed that the implementation of db_insert_into for mysql writes to a file and then uses "LOAD DATA LOCAL FILE INTO". It's not clear to me how this can possibly work if the mysql db is remote and I only have access to the JDBC port on the remote host, no file transfer, nothing. I am asking because I was looking to use the same approach for a backend I am working on that hasn't implemented "INSERT INTO ... VALUES" yet and it fails on not finding the local file.

**Comment by hadley** [comment]
I have only vague memory of how this is supposed to work, but IIRC it involves some special magic with the connection (so it does just stream the data to the server). But since I'll be getting rid of this code anyway (and moving to use dbWriteTable RMySQL directly), the question is moot.  (And probably belongs on the RMySQL repo, but again I have vague memories that maybe the behaviour is different in the dev version?)
