### ISSUE TITLE
Columns shouldn't be visible after `select` in SQL backends

### ISSUE THREAD

**Issue by craigcitro** [hadley/dplyr#1426]
(apologies if this is a dupe, but I couldn't find the original)

Currently, for some SQL backends (at least `sqlite`), columns are still visible for `filter`ing after a `select`, eg

    src_sqlite(path='Databases.db') %>% tbl("Databases") %>% select(id, name) %>% filter(description != 'temp')

will still filter on the `description` column, even though it should no longer be visible. This works as expected for dataframes:

    > df <- data_frame(x = runif(10), y = x*2)
    > df %>% select(a = x) %>% filter(y > 1)
    Error: object 'y' not found

One option here is to just `collapse` inside `select`, though it's not clear whether that would put too much pressure on the query optimizer.

**Comment by krlmlr** [comment]
Could this be a feature of SQLite: The filter appears to "work" even after inserting a compute() between select() and filter(), which leads to the conclusion that SQLite treats unknown columns in a special way in WHERE (and also ORDER BY) clauses.

**Comment by craigcitro** [comment]
I'm not sure what you mean by "feature of SQLite" -- note that the corresponding query doesn't work in SQLite, i.e. if you have a table with columns `a`, `b`, and `c`, then

    SELECT a FROM (SELECT b, c FROM t)

fails.

**Comment by momeara** [comment]
A related issue is renaming with either `rename` or `select` is invisible before applying `filter`.  The issue is that the `select` and `filter` are combined into a single `SQL` query and in postgres, it is illegal to reference an `ALIAS` in the `WHERE` clause (see http://www.postgresql.org/message-id/18195.1038530280@sss.pgh.pa.us)

As an example, 

```
library(dplyr)
library(DBI)
data_repo <- src_postgres(...)

x <- copy_to(data_repo, data_frame(a=c(1,2,3), "x")
x %>% rename(b = a) %>% collect
 Source: local data frame [3 x 1]

       b
   (dbl)
 1     1
 2     2
 3     3

> y <- x %>% rename(b=a) %>% filter(b<2)
> y$query$sql
 <SQL> SELECT "a" AS "b"
 FROM "x"
 WHERE "b" < 2.0

> y %>% collect
 Error in postgresqlExecStatement(conn, statement, ...) :
   RS-DBI driver: (could not Retrieve the result : ERROR:  column "b" does not exist
 LINE 3: WHERE "b" < 2.0
               ^
 )
```

Note that including a `compute` in between the `select` and `filter` works around the problem. 

This behavior is problematic because it is different different from how `dplyr` works for `data.frame`s and it breaks the mental model of piping the results as immutable objects through the various verbs.

Ideally, it would be nice if `dplyr` was able back out the underlying table.column names from the `ALIAS`es and use them in to construct the `WHERE` clause rather then using the alias directly.
