### ISSUE TITLE
data.table::rleid for dplyr

### ISSUE THREAD

**Issue by ckluss** [hadley/dplyr#1534]
Hi

it would be cool to have data.table::rleid in dplyr for grouping, window functions etc.

http://stackoverflow.com/questions/33507868/is-there-a-dplyr-equivalent-to-data-tablerleid

myrleid <- function(x) {
    x <- rle(x)$lengths
    rep(seq_along(x), times=x)
}

DT <- data.frame(grp=rep(c("A", "B", "C", "A", "B"), c(2,2,3,1,2)), value=1:10)
DT %<>% mutate(rlid = myrleid(grp))
DT

Greetings
Christof

**Comment by voxnonecho** [comment]
Use ```group_indices()``` to generate a unique id for each group:

    > group_indices_(df, .dots = "grp")
    # [1] 1 1 2 2 3 3 3 1 2 2

**Comment by hadley** [comment]
`group_indices()` ?

**Comment by yutannihilation** [comment]
Just for future reference, `group_indices()` is NOT equivalent to `data.table::rleid()`.

For example, suppose we want to treat first three `"a"` and last `"a"` in the data bellow are different groups:

``` r
d <- data.frame(x = c("a", "a", "a", "b", "b", "a"), stringsAsFactors = FALSE)

dplyr::group_indices(d, x)
#> [1] 1 1 1 2 2 1

data.table::rleid(d$x)
#> [1] 1 1 1 2 2 3
```

This can be implemented easily like this:

```r
my_rleid <- function(x) {
  1L + cumsum(dplyr::coalesce(x != dplyr::lag(x), FALSE))
}
```

(But, I think this is not dplyr's job. Maybe tidyr can fit since this is the similar problem which `fill()` tries to solve in that they both are about how to work with consecutive rows.)
