### ISSUE TITLE
Filter function issue

### ISSUE THREAD

**Issue by polip** [hadley/dplyr#1655]
Simple filtering (target <- filter(Fit.Data.Test, Account.Count==18)) is throwing out following error:
data_frames can only contain 1d atomic vectors and lists

Other dplyr functions are working  normally. 
I don't understand, yesterday was all fine.

R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

DPLYR 0.4.3

**Comment by romainfrancois** [comment]
Please make this reproducible. We do not have `Fit.Data.Test`

**Comment by joel23888** [comment]
@polip Notwithstanding that you generally need to provide a minimum reproducible example, can I suggest that you try using dplyr::filter instead of just filter? If that solves the problem then it is likely a masking issue. See e.g. http://www.ats.ucla.edu/stat/r/faq/referencing_objects.htm for further details on this.

**Comment by polip** [comment]
Sorry I didn't put reproducible example. Anyway, it was a masking issue. Thank you for your help.
