### ISSUE TITLE
failure to report error when piping with no input

### ISSUE THREAD

**Issue by Nicktz** [hadley/dplyr#1825]
When piping one of the standard dplyr commands without an argument or brackets, it produces a 'print' of the tbl_df().

E.g.: 
x <- data.frame(Name = 10 ) %>% tbl_df()
x %>% mutate
is equivalent to:
print(x).

It should, perhaps, rather produce an error stating that no argument had been given? Not sure why it should produce a print instead, as it most likely would not be the intention of the coder to print the tbl using a no-argument pipe.

This created a bug in our code when we accidentally deleted a part of our code but was not alerted with an error, and we assumed (wrongly) what followed after the standalone 'mutate_' was the (arguments).

**Comment by krlmlr** [comment]
`x %>% mutate` is equivalent to `mutate(x)`, which prints the result (i.e., x unchanged) if executed as top-level expression. So the issue here seems to be if mutate (or filter, arrange, ...) should warn/err if no *additional* arguments are passed.

Omitting the parentheses is not an error with the pipe operator, which is implemented in the [magrittr package](https://github.com/smbache/magrittr).

**Comment by Nicktz** [comment]
Although I would suggest that omitting the parentheses should then produce an error? Else why would the modeler include X %>% mutate? I cannot think of a reason other than it being a mistake?

**Comment by hadley** [comment]
This is design decision by magrittr
