### ISSUE TITLE
Rename and export probe_colwise_names

### ISSUE THREAD

**Issue by jlegewie** [hadley/dplyr#2129]
It is easy to support other classes with methods for `mutate_`, `summarise_`, `mutate_at` etc. `*_if()` variants, however, do not work with databases and we are unable to directly support it in spatial objects in `spdplyr`. Here are some thoughts from @lionel- : 

> The easy fix is to make probe_colwise_names() an exported generic. I'm not sure we want to abstract out function mapping in the dplyr interface though. So I don't know what can be done here.
> 
> Maybe have a generic map in purrr. I think we need a s3map() family in purrr. But until purrr depends on dplyr (there are plans to decouple) we can't have dplyr depend on purrr anyway.

https://github.com/mdsumner/spdplyr/issues/10#issuecomment-247679269

**Comment by hadley** [comment]
Lets make `probe_colwise_names()` generic. We'll just need to come up with a slighter shorter name. It might be reasonable for the default method to call `collect()`  or `as.data.frame()` (for data bases, n will need be set to a small number), since I think most often the predicates are used for type information.
