### ISSUE TITLE
Get rid of conflicts with the "stats" package

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2195]
Currently only `filter` and `lag`. Suggestions:

- `filter()` -> `where()`, should look natural to SQL users but is not a verb; `filter_rows()`, is a verb but long
- `lag()` -> `lag2()` or `vlag()` (for vector lag); don't have a good one here; unfortunately, `stats` already defines `lag.default()`

Deprecation first via messages (once per session), later via warnings (once per session), much later by removing. I'd argue it's worth the effort.

**Comment by lionel-** [comment]
maybe `keep_where()`? And `drag()` for lag? Though it feels wrong to change the reference to `lag` as it is an established modelling term.

> vlag() (for vector lag)

If I'm not mistaken the vector prefix will be `vec_` in vctrs, with `atm_` for atomic vectors and `lst_` for generic vectors.

**Comment by krlmlr** [comment]
`keep_where()` is longish too, but how about `keep()` (with an optional alias to `keep_where()`)?

`vec_lag()`?

**Comment by lionel-** [comment]
`keep()` is a function in purrr :(

**Comment by krlmlr** [comment]
Oh. But then `keep_rows()` looks more natural to me.

**Comment by burkovae** [comment]
`having` or `being` maybe ? if `select` specifies rows, then one could naturally say `select stuff having id == x`.

**Comment by krlmlr** [comment]
@hadley: Does any of these options appeal to you?

**Comment by hadley** [comment]
TBH, no.  I think it's too late to change.

**Comment by krlmlr** [comment]
Both `stats::filter()` and `stats::lag()` operate on time series. We could do something nice if the user calls us with a time series object. ?

**Comment by hadley** [comment]
I like that idea!

**Comment by beberking** [comment]
Dear dplyr authors,

Could you please reconsider how you handle overwriting stats::lag? Loading dplyr makes it very difficult to use the stats::lag function in econometrics formula, as I would need to rewrite all my models and it would make them a lot more difficult to read.

Would it be possible for you to forward time series to stats::lag or use an S3 method?

Best regards,
Bertrand

**Comment by lionel-** [comment]
@beberking It is too late to reconsider this decision but see https://github.com/r-lib/conflicted for some experiments to make it easier to deal with symbol conflicts.

About forwarding ts objects to `stats::lag()` this would probably cause more harm because we can't redirect simple objects anyway and there would be more chance that users are unaware of the masking.

**Comment by hadley** [comment]
Also you can do `lag <- stats::lag` so it’s not hard to work around.

**Comment by lionel-** [comment]
Though `lag` is a likely candidate for a variable name so doing it this way makes scripts brittle.

**Comment by beberking** [comment]
Thank you for your answer. I am sorry to insist, but I don't see why dplyr couldn't at least try to keep something based on S3 methods, which would play much nicer with conflicts to my mind.

For instance, what do you think about overriding only lag.default instead of lag, so the user would be able to define properly lag.ts as he/she wishes? It would still override the stats::lag behaviour by default, but it would be more flexible for the users, especially those interested in time series.

Best regards,
Bertrand

**Comment by hadley** [comment]
We have tried in the past and it does not allow us the flexibility needed. It was a mistake but I believe that changing our approach now would have a larger negative effect than leaving it as is. Regardless, it is not up for discussion, and even if it was, comments on a closed issue is not the way to handle it.
