### ISSUE TITLE
Revisit definition of slice(df)

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2252]
Currently returns all rows, but it's not tested anywhere. I think it should return an empty data frame instead, and slice(df, i1, i2) should be the same as slice(df, c(i1, i2)).

@hadley: Thoughts?

**Comment by hadley** [comment]
I think the motivation was for `filter(x)` and `slice(x)` to give identical results, but maybe that's wrong because an empty logical should be treated as selecting all rows, whereas an empty integer should be treated as selecting no row.

Equally, `filter()` ANDs together the inputs, and here you're proposing (effectively) that slice OR's together the inputs.

**Comment by krlmlr** [comment]
Yes, that's the way I'd see it -- perhaps not even OR, but UNION ALL. FWIW, slice(df, i1, i2) currently throws an error.

**Comment by hadley** [comment]
Can you tackle this one too please? I think it should be a one-line change in `slice_impl()`.

**Comment by krlmlr** [comment]
I have now found the [test](https://github.com/hadley/dplyr/blob/f39db50921110c3d23612cc81a7b3e027c0b3d1c/tests/testthat/test-slice.r#L23-L25). It seems that `slice()` intentionally accepts either 0 or one args, negative values are treated as exclusions. The current behavior actually makes some sense, I see no reason to change it.

We could still consider supporting multiple arguments to slice(), but only after #2311.
