### ISSUE TITLE
mutate_each_ fails with the new version of dplyr 

### ISSUE THREAD

**Issue by aipsa** [hadley/dplyr#2429]
For the 0.5.0 version of dplyr 
```r
library(dplyr)
head(mutate_each_(mtcars, ~round(., 2), ~-matches("variable")))
#Error: is.fun_list(calls) is not TRUE
```

For the 0.4.3 version it works :
```r
library(dplyr)
head(mutate_each_(mtcars, ~round(., 2), ~-matches("variable")))
#>    mpg cyl disp  hp drat    wt  qsec vs am gear carb
#> 1 21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
#> 2 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
#> 3 22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
#> 4 21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
#> 5 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
#> 6 18.1   6  225 105 2.76 3.460 20.22  1  0    3    1
```

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/jennybc/reprex#what-is-a-reprex)", and follow the advice further down the page.

**Comment by aipsa** [comment]
Done !

**Comment by hadley** [comment]
You need to use `funs()` now, but you'd probably be better switching to `mutate_at()`.

```R
mutate_each_(mtcars, funs(round(., 2)), ~-matches("variable"))
mutate_at(mtcars, vars(-matches("variable")), funs(round(., 2)))
```

Expect this to get some polishing in the next version.
