### ISSUE TITLE
bind_rows() can't create list-cols

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#2493]
```r
library(dplyr)
x <- list(
  list(a = "a", n = 1:2),
  list(a = "A", n = 3:7)
)

bind_rows(x)
#> Error in bind_rows_(x, .id) : incompatible sizes (1 != 2) 
```

Originally at https://github.com/hadley/purrr/issues/264. 

This would make `bind_rows()` more permissive, and would make the type of the columns in the output somewhat harder to predict.

**Comment by zeehio** [comment]
My two cents:

`bind_rows` can create list-cols:

```r
library(dplyr)
x <- list(
  list(a = "a", n = list(1:2)),
  list(a = "A", n = list(3:7))
)

bind_rows(x)
```
```
# A tibble: 2 × 2
      a         n
  <chr>    <list>
1     a <int [2]>
2     A <int [5]>
```

So this issue could be retitled as: **What should `bind_rows()` do with inconsistent lengths?**

If `bind_rows(list(a = "a", n = 1:2))` created a list column in `n`, then:
- What about `bind_rows(list(a = c("a", "b", "c"), n= 1:2))`? Do we set `a` as a list column repeated 3 times or `n` as a list column repeating two times?
- What if one provides more arguments to `bind_rows`? 

The answer for all this cases would then need to be something like: *whenever it is possible return a vector column, otherwise return a list column*. Even if this is feasible, I would not think it is a great approach for these three reasons:
- `bind_rows` already supports list-columns (as shown).
- There are ambiguities for which I don't see an easy solution.
- Users who expect vector columns and make mistakes will *get an unexpected result instead of an error*. (most important to me)

But of course, feel free to follow whatever you decide. :+1:

**Comment by lionel-** [comment]
Should be thought of in the context of #1676

**Comment by lionel-** [comment]
@hadley @jennybc Could the extract methods take an optional mapping function?

Then before binding the lists you'd do:

```r
x <- list(
  list(a = "a", n = 1:2),
  list(a = "A", n = 3:7)
)

x <- map(x, "n", as_list)
```

Linked to `modify_depth()`, but this somehow feels natural. Though it does feel a little odd that the depth of the output changes as a function of whether you map into the innards of the list or just extract them.

**Comment by hadley** [comment]
Yeah, I now think that this would make `bind_rows()` too permissive. 

You can now solve in purrr with an explicit call to `extract()`:

```R
x <- list(
  list(a = "a", n = 1:2),
  list(a = "A", n = 3:7)
)

x <- map(x, ~ as_list(extract(., "n"))
```
