### ISSUE TITLE
Order-of-magnitude performance drop, possibly due to rlang

### ISSUE THREAD

**Issue by krlmlr** [hadley/dplyr#2557]
@lionel-: I see a substantial performance drop for several verbs somewhere around the introduction of rlang, but I can't measure intermediate versions because we didn't think about pinning the rlang revision back then, and older code doesn't work with current rlang. The benchmark code is here: https://github.com/krlmlr/dplyr.benchmark/blob/a27d672a19b80a168a0bffc626d8050a41ae18e2/tests/testthat/code/microbenchmark.R

To rerun the benchmark to detect which particular revision introduced the slowdown, I could use a list of  rlang revisions for each dplyr revision between f39db50 and 4c5a978. Or we could just profile and see where the time is spent.

One of the things that have changed is the use of `overscope_eval()`. Could this be the reason? Do we really need to build the overscope for each call?

![download 5](https://cloud.githubusercontent.com/assets/1741643/24176198/d71ad452-0e9a-11e7-8181-8aa8447e2a4a.png)
![download 4](https://cloud.githubusercontent.com/assets/1741643/24176199/d7342dc6-0e9a-11e7-907a-2d168dd496b4.png)
![download 3](https://cloud.githubusercontent.com/assets/1741643/24176197/d717ccd0-0e9a-11e7-9c31-0e5f96138aa1.png)
![download 2](https://cloud.githubusercontent.com/assets/1741643/24176196/d717a7d2-0e9a-11e7-9a01-72540d251fda.png)
![download 1](https://cloud.githubusercontent.com/assets/1741643/24176195/d7174116-0e9a-11e7-83b5-9799f225b2ee.png)

**Comment by lionel-** [comment]
> Do we really need to build the overscope for each call?

The overscope in only built once. Could it be the language cell allocation for creating a quosure? And the callback to R? Once for each group it adds up. I'll look into it thanks for the report.

**Comment by krlmlr** [comment]
We had the callback to R before. I wonder if `overscope_eval()` is doing too much, and should be split into a one-time and a recurring part.

**Comment by lionel-** [comment]
`overscope_eval()` is already doing the bare minimum: rechaining (not rebuilding) the overscope to the currently evaluated quosure, and evaluating the RHS of the current quosure in the overscope.

**Comment by krlmlr** [comment]
Do we really need to rechain between groups?

**Comment by lionel-** [comment]
yes, the overscope might have been rechained to another enclosure in the previous call. That will happen when evaluating quosures which self-evaluate to their RHS.

**Comment by lionel-** [comment]
setting the parent of an environment should be pretty fast no? that's just setting a pointer I presume

**Comment by krlmlr** [comment]
There is optimization potential even in the R code (e.g., I don't think you want to call `f_env<-` if it doesn't change).

How can the overscope be rechained to another closure? Each overscope is used only for one expression.

**Comment by lionel-** [comment]
tidyeval works because we are treating quosures as reified promises. You can modify a captured expression flexibly by unquoting scoped expressions (quosures). Then these quosures self-evaluate like promises. But we do need to rechain them to the overscope before we evaluate their RHS.

But now that I think of it, the parent of the overscope is reset to the original parent once a quosure has finished evaluating, so the call to `overscope_eval()` might be superfluous here.

Also I wonder if we should be a bit naughty and use `ENCLOS(x) = env` when we rechain. Since we are resetting the parent in an `on.exit()` expression, this shouldn't have adverse effects.

**Comment by lionel-** [comment]
the expression evaluated in a `mutate()` call might be: `~toupper(~letters)`. We have a definition `~` in the overscope that makes it self-evaluate. So when `toupper(~letters)` gets evaluated, it first evaluates the argument `~letters`, which self-evaluates, then it evaluates `toupper(letters)` with the value of `letters`. When a quosure self-evaluate, its enclosure is chained on top of the overscope and the RHS is evaluated in the overscope, where all the special definitions live.

> why rechaining for each group is important

As mentioned above, that may not be necessary because the parent of the overscope is reset after each quosure evaluation.

**Comment by lionel-** [comment]
@krlmlr could you update the graph with https://github.com/hadley/dplyr/pull/2560 please?
