### ISSUE TITLE
Error: enc2utf8(col_names(col_labels, sep = sep))

### ISSUE THREAD

**Issue by shashi108** [hadley/dplyr#2579]
`for(i in c("B1","B2","B3","B4")){
    
    dataset_miss_sc<-sprintf("t_%s",i)
    
    dataset_miss_sc<-subset(SCIM_Data_Analysis_L4121,Visit == i)
    
    
    dataset_set_sc<-sprintf("sc_%s",i)  
    dataset_set_co_sc<-dataset_set_sc
    dataset_set_sc<-dataset_miss_sc %>%
      gather(key = variable, value = value, SCIM_SelfCare_SubScore:SCIM_TotalScore) %>%
      group_by(Visit, variable) %>%
      summarise(mean =paste(sum(is.na(value)),"/",nrow(dataset_miss_sc),"(",round(sum(is.na(value))*100/nrow(dataset_miss_sc),digit=1),"%)"))%>%
      spread(variable, mean,drop=F)
    
    assign(dataset_set_co_sc,dataset_set_sc,.GlobalEnv)
  }`

I got error: Error in enc2utf8(col_names(col_labels, sep = sep)) :  argumemt is not a character vector

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/jennybc/reprex#what-is-a-reprex)", and follow the advice further down the page.
