### ISSUE TITLE
Plyr compatibility

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#29]
Make sure dplyr and plyr work together nicely when loaded together.

**Comment by winampman** [comment]
I just want to reiterate what holgerbrandl said about rename in this thread.
I have a lot of code written using plyr. rename is a function I used a lot. 
plyr:
   rename(df, c(old="new"))

Unfortunately when I load plyr, then load dplyr, the 2 renames are incompatible because the syntax is different:. 
dplyr:
    rename(df, new=old)

I cannot run my code with dplyr unless I do one of the following:

- go back and change all the plyr rename syntax to the dplyr rename syntax
- go back and change all the plyr renames to plyr::rename
- or the simplest solution, add this to the top of my code: rename <- plyr::rename

Can we change the dplyr::rename syntax to match plyr syntax? And if not, can we at least change the dplyr function name to something else? (like rename_vars...)

Thanks, I've been enjoying dplyr so far except for this one issue.

**Comment by krlmlr** [comment]
With current `plyr` and `dplyr`, there are only a few true incompatibilities. In a nutshell:

- `mutate` -> `dplyr::mutate`
    - row names are lost
- `summari[sz]e` -> `dplyr::summari[sz]e`
- `arrange(df, ...)` -> `dplyr::arrange(.data, ...)`
    - (are the three above really the same now in `plyr` and `dplyr`?)
- `count(df, vars, wt_var)` -> `dplyr::count_(x, vars, wt, sort = FALSE)`
    - rename `n` column to `freq`
- `rename(x, replace, warn_missing)` -> `dplyr::rename_(.data, replace)`
    - `replace` needs to be massaged
    - `warn_missing` is always `TRUE`
- `desc()`, `failwith()`, `id()` -> identical with `dplyr::...`

This is what *technically* overlaps when you attach both `plyr` and `dplyr`. See http://krlmlr.github.io/pdlyr for more detail.

**Comment by friendly** [comment]
The `Lahman` package, at https://github.com/cdalzell/Lahman, is currently being tested for a new 5.0-0 version on the branch https://github.com/cdalzell/Lahman/tree/feature/2015-data-update.

V. 4.0-1 used `plyr` in quite a few examples, and in https://github.com/cdalzell/Lahman/issues/20 the issue of replacing `plyr` with `dplyr` is raised.  This dplyr thread is now fairly old, so I'm wondering what compatibility issues still remain.

**Comment by hadley** [comment]
I think this has now been left so long that it's not really worth fixing in dplyr.  If you need functions from both packages, I recommend that you attach dplyr with `library(dplyr)` then use `::` to refer to functions from plyr.

**Comment by friendly** [comment]
Thanks; All problems re: Lahman were resolved long ago.
