### ISSUE TITLE
summarise_each_q naming consistency

### ISSUE THREAD

**Issue by tverbeke** [hadley/dplyr#442]
Currently the naming of output variables does not seem consistent:

```
summarise_each_q(mtcars, funs = "mean", vars = "disp")
#       disp
# 1 230.7219

summarise_each_q(mtcars, funs = c("mean", "sd"), vars = "disp")
#       mean       sd
# 1 230.7219 123.9387

summarise_each_q(mtcars, funs = c("mean", "sd"), vars = c("disp", "cyl"))
#   disp_mean cyl_mean  disp_sd   cyl_sd
# 1  230.7219   6.1875 123.9387 1.785922
```

Maybe in each of the cases ```<var>_<fun>``` could be used, as in
```
summarise_each_q(mtcars, funs = "mean", vars = "disp")
#    disp_mean
# 1 230.7219

summarise_each_q(mtcars, funs = c("mean", "sd"), vars = "disp")
#  disp_mean  disp_sd
# 1 230.7219 123.9387

summarise_each_q(mtcars, funs = c("mean", "sd"), vars = c("disp", "cyl"))
#   disp_mean cyl_mean  disp_sd   cyl_sd
# 1  230.7219   6.1875 123.9387 1.785922
```

**Comment by lionelgit** [comment]
If `summarise()` gets the ability to return multi-row outputs (see #154), then it could make sense for `summarise_each()` to report one row by function with a new `.funs` column.

This way we'd get a tidy data frame.
See also this [SO question](http://stackoverflow.com/questions/27879638/use-dplyrs-summarise-each-to-return-one-row-per-function).

**Comment by LaDilettante** [comment]
The issue here is not just naming inconsistency but also dplyr's behavior to add variables when there are two summarizing functions and replace existing variables when there is only one summarizing function (see #1259)

I would suggest that dplyr adds variable and renames them (`myvar_min`) when the user gives a named function, e.g. `by_species %>% mutate_each(funs(blah = min))`. In this case, the columns will be `Sepal.Length`, `Sepal.Width`, ... , `Sepal.Length_min`, `Sepal.Width_min`, ...

This way, there is no need for an extra argument and the behavior is consistent with when there are multiple summarizing functions specified.

**Comment by hadley** [comment]
@LaDilettante I like that idea!
