### ISSUE TITLE
Should data_frame() forbid POSIXlt?

### ISSUE THREAD

**Issue by hadley** [hadley/dplyr#813]
or in general, any list with a class? Unless it's been specifically designed to work as a list column, it will only have the right number of elements by chance:

```R
mod <- lm(mpg ~ wt, data = mtcars)
data_frame(x = 1:12, y = mod)

data_frame(x = 1:11, y = as.POSIXlt(Sys.time()))
```

**Comment by wshatpud** [comment]
I don't think I like this decision.  I agree that POSIXct is the target structure, but, when you get POSIXlt data from another package (e.g., weatherData::getSummarizedData), it's nice to be able to convert it with mutate (i.e., inside the dplyr environment), rather than having to flip back to older ways.  It's just a simple dataframe %>% mutate(Date = as.POSIXct(Date)), and dataframe is just a data frame, not a tbl_df (or tibble, I guess now).
