### ISSUE TITLE
summarize fails with data.table but works with data.frame

### ISSUE THREAD

**Issue by rdbisch** [hadley/dplyr#883]
summarize fails on data.table when group_by called with a derived function.  Works as expected with data.frame

```R
require(data.table)
require(dplyr)
test.data <-
    data.frame(
            x1 = rnorm(100),
            x2 = rnorm(100),
            y = rnorm(100) )

test.data %>%
    group_by(round(x1,2), round(x2,2)) %>%
    summarize(mean=mean(y))

#Source: local data frame [100 x 3]
#Groups: round(x1, 2)
#
#   round(x1, 2) round(x2, 2)       mean
#1         -2.19         0.77  0.4624394
#2         -2.07         0.39  0.7820141
#3         -1.80        -0.54 -1.1932833
#4         -1.60         1.58  1.1222378
#5         -1.59        -1.85  2.3900652
#6         -1.50         0.44 -0.7027764
#7         -1.48         0.21  0.1983198
#8         -1.19         2.21  0.4903789
#9         -1.18        -0.95 -0.9614805
#10        -1.18        -0.85 -0.1244882
#..          ...          ...        ...

test.data.table <- data.table(test.data)

test.data.table %>%
    group_by(round(x1,2), round(x2,2)) %>%
    summarize(mean=mean(y))

#Error in `[.data.table`(`_dt`, , list(mean = mean(y)), by = `_vars`) : 
#  'by' is a character vector length 2 but one or more items include a comma. 
# Either pass a vector of #column names (which can contain spaces, but no commas), 
# or pass a vector length 1 containing #comma separated column names. See ?data.table 
# for other possibilities.
```

**Comment by jonboiser** [comment]
Here's what I think might be a variation on this issue.

```
aggiris_dt_dplyr <- function(agg_fun = mean) {
    iris_dt <- data.table(iris)
    iris_dt %>% 
        group_by(Species) %>%
        summarize(V = agg_fun(Sepal.Width))
}


aggiris_df_dplyr <- function(agg_fun = mean) {
    iris %>% group_by(Species) %>%
        summarize(V = agg_fun(Sepal.Width))
}


aggiris_dt_default <- function(agg_fun = mean) {
    iris_dt <- data.table(iris)
    iris_dt[, list(V = agg_fun(Sepal.Width)), by = "Species"]
}

aggiris_dt_dplyr() # fails: doesn't resolve agg_fun = mean promise
aggiris_dt_default() # ok, seems to rule out data.table
aggiris_df_dplyr() # ok
```

It seems to be an interaction between how the `...`'s and data.table's API for aggregation interact.

**Comment by pimentel** [comment]
@rdbisch, this issue seems to be in `dplyr:::dt_subset`. When it calls data table, the call is evaluated to something like this:

```{r}
set.seed(42)
test.data <-
  data.frame(
    x1 = rnorm(100),
    x2 = rnorm(100),
    y = rnorm(100) )

test_dt <- data.table(test.data) %>%
  mutate(round(x1, 2), round(x2, 2))
test_dt[, list(mean = mean(y)), by = c("round(x1, 2)", "round(x2, 2)")]
```

Note that even though you didn't explicitly create the space in the `round` calls, it gets put there by `lazy_eval::all_dots`. Then `data.table` complains because it doesn't like the space in `round`, even though it doesn't care that the space is there in the column name. A way to solve this is to change the way that `dt_subset` works and replace the statement:

```{r}
    call <- substitute(`_dt`[i, j, by = `_vars`], args)
```

with an expression. What I mean is, instead of using the string statement, the call looks like this:

```{r}
> res <- test_dt[, list(mean = mean(y)), by = list(round(x1, 2), round(x2, 2))]
> head(res)
   round round       mean
1:  1.37  1.20 -2.0009292
2: -0.56  1.04  0.3337772
3:  0.36 -1.00  1.1713251
4:  0.63  1.85  2.0595392
5:  0.40 -0.67 -1.3768616
6: -0.11  0.11 -1.1508556
```

yay! this statement works... but notice the column names are all mucked up. I might be able to provide a fix to (need to brush up on some NSE). If I have time this weekend I might do so.

Note, a work around is to simply use `mutate` (dplyr does this internally anyway, you just don't see it):

```{r}
data.table(test.data) %>%
  mutate(round_x1 = round(x1), round_x2 = round(x2)) %>%
  group_by(round_x1, round_x2) %>%
  summarize(mean=mean(y))
```

@jonboiser Yeah... I don't know. NSE, man. Would have to look a bit deeper

**Comment by pimentel** [comment]
BTW, @jonboiser, I might consider opening another issue as I don't think this is related to the original issue.

**Comment by jonboiser** [comment]
@pimentel The issues are pretty close, so could we explore the data.table/dplyr interop issue in the OP and maybe that will point me down the right path for my issue with the NSE twist.

Do you know which files we should be looking at?

**Comment by pimentel** [comment]
@jonboiser I made a pull request for the original issue here: https://github.com/hadley/dplyr/pull/993 my guess is the issue you're seeing might be happening in `summarise_.data.table`, though, I'm wildly speculating.

**Comment by jonboiser** [comment]
Cool. I'll install your fork and give it a try.

**Comment by jonboiser** [comment]
@pimentel Your patch fixes my issue too. Hopefully it gets accepted soon. :+1:

**Comment by pimentel** [comment]
ha! nice! thanks for taking a look, @jonboiser!

**Comment by krlmlr** [comment]
I'm seeing a perhaps related error with using data.table in R packages. I cannot build a package that contains the following code in one of its R files (as standalone expression):

```
summarize(tbl_dt(iris), n = n())
```

Example package: https://github.com/krlmlr/dplyr.summarize.dt

Relevant Travis result: https://travis-ci.org/krlmlr/dplyr.summarize.dt/builds/63657065#L1027

(A different error occurs if `data.table` is not part of `Depends`, but the Travis builds don't reflect it because `data.table` was not installed automatically.)
