### ISSUE TITLE
Mutate and ifelse fails with unequal group sizes

### ISSUE THREAD

**Issue by ebuz** [hadley/dplyr#942]
Mutating a data.frame and creating a conditional variable fails if groups are unequal in size (dplyr version 0.4.1.9000). This is a working example:

```R
df <- data.frame(type = c('a', 'a', 'a', 'b', 'b'), value = rnorm(5))

#doesn't work
df %>%
    group_by(type) %>%
    mutate(scaled = scale(value), half = ifelse(scaled > 0, 'high', 'low'))

#equal sized groups work
df[2:5,] %>%
    group_by(type) %>%
    mutate(scaled = scale(value), half = ifelse(scaled > 0, 'high', 'low'))

#transform works
df %>%
    group_by(type) %>%
    transform(scaled = scale(value)) %>%
    transform(half = ifelse(scaled > 0, 'high', 'low'))
```

Using mutate then transform also fails and the reverse (calling transform then mutate) works fine.

**Comment by astamm** [comment]
Hi,

I think I got yesterday a nice workaround by creating the mutate_if verb.

It has already been discussed a lot in other posts and skranz provided an efficient mutate_if function in his dplyrExtras package on github.

However, his version relies on transforming your data into a data.table and then effectively handle the mutate_if using functions from data.table instead of dplyr, which can results in odd behaviors in future chain elements like group_by.

I propose the following, based solely on dplyr already existing verbs, that achieve same or even slightly better performance than dplyrExtras::mutate_if (says microbenchmark):
mutate_if <- function(data, condition, ...) {
  condition <- lazyeval::lazy(condition)
  args <- lazyeval::lazy_dots(...)
  mutate_if_(data, condition, .dots = args)
}
mutate_if_ <- function(data, condition, ..., .dots = list(...)) {
  condition <- lazyeval::lazy_eval(condition, data)
  data1 <- dplyr::filter(data, !condition)
  data2 <- dplyr::filter(data, condition)
  data2 <- dplyr::mutate_(data2, ..., .dots = .dots)
  dplyr::bind_rows(data1, data2)
}

Be careful that the row order will then be a little bit different. I thought about outputting the dataset in the original row order, but, as of now, I can’t think of a good reason so I am fine with that.

I haven’t tested it with grouped data, but since it relies only on dplyr verbs, it should be fine I guess.

Hope that helps,
-Aymeric

On Feb 2, 2015, at 12:28 PM, Esteban <notifications@github.com<mailto:notifications@github.com>> wrote:


Mutating a data.frame and creating a conditional variable fails if groups are unequal in size (dplyr version 0.4.1.9000). This is a working example:

df <- data.frame(type = c('a', 'a', 'a', 'b', 'b'), value = rnorm(5))

#doesn't work
df %>%
    group_by(type) %>%
    mutate(scaled = scale(value), half = ifelse(scaled > 0, 'high', 'low'))

#equal sized groups work
df[2:5,] %>%
    group_by(type) %>%
    mutate(scaled = scale(value), half = ifelse(scaled > 0, 'high', 'low'))

#transform works
df %>%
    group_by(type) %>%
    transform(scaled = scale(value)) %>%
    transform(half = ifelse(scaled > 0, 'high', 'low'))

Using mutate then transform also fails and the reverse (calling transform then mutate) works fine.

**Comment by astamm** [comment]
After giving it some more thoughts, I came up with mutate_if and mutate_ifelse verbs:
mutate_if <- function(data, condition, ...) {
  condition <- lazyeval::lazy(condition)
  args <- lazyeval::lazy_dots(...)
  mutate_if_(data, condition, .dots = args)
}
mutate_if_ <- function(data, condition, ..., .dots = list(...)) {
  ncondition <- lazyeval::interp(~ !cond, cond = condition)
  mdata <- dplyr::mutate_(data, ..., .dots = .dots)
  mdata <- dplyr::filter_(mdata, condition)
  data <- dplyr::filter_(data, ncondition)
  dplyr::bind_rows(data, mdata)
}
mutate_ifelse <- function(data, condition, ...) {
  condition <- lazyeval::lazy(condition)
  args <- lazyeval::lazy_dots(...)
  nargs <- length(args)
  if (nargs %% 2 != 0)
    stop("There should an even number of input mutations for correct specification of if and else behaviors.")
  even <- args[seq(1, nargs, by = 2)]
  odd <- args[seq(2, nargs, by = 2)]
  mutate_ifelse_(data, condition, .dots.if = even, .dots.else = odd)
}
mutate_ifelse_ <- function(data, condition, ..., .dots.if = list(...), .dots.else = list(...)) {
  ncondition <- lazyeval::interp(~ !cond, cond = condition)
  cdata <- dplyr::mutate_(data, ..., .dots = .dots.if)
  cdata <- dplyr::filter_(cdata, condition)
  data <- dplyr::mutate_(data, ..., .dots = .dots.else)
  data <- dplyr::filter_(data, ncondition)
  dplyr::bind_rows(data, cdata)
}

that solely rely on dplyr already existing verbs.

The difference is that mutate_if only modify the entries that satisfy the condition. Hence, in creating new variables upon if using mutate_if, all entries that do not fulfill the condition will be filled in with NA.
Conversely, mutate_ifelse allows you to specify what happens to entries that satisfy the condition and to entries that do not.

Note that one could think of inverting the mutate/filter sequence of operations in the functions above and that would eventually yield a slight (very slight) benefit in computation time because the mutate operations then only happens to the rows of interest rather than to the whole dataset while we are interested only to a subset. However, if we do that, we end up mutating tables that are different from the original one with possibly dropped levels or other inconsistencies because of the filtering that would have happened first. Hence, I find this is safer and fully supports group_by operations.

The end tbl_df will indeed have rows in a different order than the original one. But it is also good practice to make sure your data is ordered as you want with arrange before using functions such as first or last that rely on ordering.

Example of use:
library(dplyr)
df <- data_frame(type = c('a', 'a', 'a', 'b', 'b'), value = rnorm(5))
df %>%
  group_by(type) %>%
  mutate_ifelse(type == "a", value2 = first(value), value2 = 1, value3 = last(value), value3 = 2)

n = 1e6
df = data_frame(a= sample(1:3,n,replace=TRUE),
                b= sample(1:100,n,replace=TRUE),
                x=rnorm(n))
timing <- microbenchmark(times = 10L,
                         mutate(df, x=ifelse(a==2,x+100,x)),
                         mutate_if(df, a==2, x=x+100),
                         mutate_ifelse(df, a==2, x=x+100, x=x))
print(timing)

Best,
-Aymeric

On Feb 2, 2015, at 12:28 PM, Esteban <notifications@github.com<mailto:notifications@github.com>> wrote:


Mutating a data.frame and creating a conditional variable fails if groups are unequal in size (dplyr version 0.4.1.9000). This is a working example:

df <- data.frame(type = c('a', 'a', 'a', 'b', 'b'), value = rnorm(5))

#doesn't work
df %>%
    group_by(type) %>%
    mutate(scaled = scale(value), half = ifelse(scaled > 0, 'high', 'low'))

#equal sized groups work
df[2:5,] %>%
    group_by(type) %>%
    mutate(scaled = scale(value), half = ifelse(scaled > 0, 'high', 'low'))

#transform works
df %>%
    group_by(type) %>%
    transform(scaled = scale(value)) %>%
    transform(half = ifelse(scaled > 0, 'high', 'low'))

Using mutate then transform also fails and the reverse (calling transform then mutate) works fine.

**Comment by hadley** [comment]
The problem is that scale makes a matrix. This works:

```R
df <- data.frame(type = c('a', 'a', 'a', 'b', 'b'), value = rnorm(5))

df %>%
  group_by(type) %>%
  mutate(scaled = as.numeric(scale(value)), half = ifelse(scaled > 0, 'high', 'low'))
```
