### ISSUE TITLE
When filter() gets a formula object, it modifies it by reference

### ISSUE THREAD

**Issue by lionel-** [hadley/dplyr#971]
This happens when we forget to add an underscore to use the non-NSE version:

```{r}
my_filter <- ~ am == 1
mtcars %>% filter(my_filter)
## Error: filter condition does not evaluate to a logical vector. 
```

Now, `my_filter` contains the actual `am` object instead of just its name.

**Comment by astamm** [comment]
I think you have to use the SE version filter_ of filter in this case.

On Feb 16, 2015, at 6:06 AM, Lionel Henry <notifications@github.com<mailto:notifications@github.com>> wrote:


This happens when we forget to add an underscore to use the non-NSE version:

my_filter <- ~ am == 1
mtcars %>% filter(my_filter)
## Error: filter condition does not evaluate to a logical vector.

Now, my_filter contains the actual am object instead of just its name.

**Comment by lionel-** [comment]
Sure, but this is no reason for `filter()` to mess with my formula ;-)

**Comment by hadley** [comment]
This isn't a crasher, so putting off until 0.5

**Comment by romainfrancois** [comment]
Hmm. I don't get it, since we do `duplicate` it in the `Lazy` class: 

```
        inline SEXP expr() const {
            return Rf_duplicate(data[0]) ;
        }
```
